/* Banco de Questões — IBGE PSS 02/2026 · estilo Instituto Avalia
   60 questões: 18 Português · 12 Raciocínio Lógico · 30 Conhecimentos Específicos */
const QUESTOES = [

/* ============ LÍNGUA PORTUGUESA (18) ============ */
{ id:"pt_q01", disc:"pt", top:"Interpretação",
  stem:"“O recenseador deve registrar a informação declarada pelo morador, ainda que ela contrarie sua percepção pessoal.” Do trecho, infere-se corretamente que:",
  alts:["o recenseador pode corrigir dados que julgar equivocados.","a percepção do recenseador prevalece em caso de dúvida.","o registro se baseia na declaração do morador, e não no juízo do recenseador.","o morador é obrigado a comprovar documentalmente o que declara.","a informação só é registrada quando recenseador e morador concordam."],
  correct:2,
  why:"“Ainda que” introduz concessão: mesmo discordando, o recenseador registra o que foi declarado. As demais alternativas contradizem o trecho ou acrescentam exigências que não estão no texto — erro clássico de extrapolação." },

{ id:"pt_q02", disc:"pt", top:"Parônimos",
  stem:"Assinale a frase em que o par ratificar/retificar foi empregado corretamente:",
  alts:["O coordenador ratificou o endereço errado no formulário, corrigindo-o.","O supervisor retificou sua confiança na equipe, elogiando o trabalho.","A comissão ratificou a decisão anterior, confirmando-a integralmente.","O analista retificou o acordo, mantendo todos os termos originais.","O chefe ratificou o número incorreto, trocando-o pelo certo."],
  correct:2,
  why:"RA-tificar = confirmar (RAtificar reafirma); RE-tificar = corrigir (REtificar refaz). Só a alternativa C usa “ratificou” com sentido de confirmar. A, D e E usam confirmação onde o sentido é correção (ou vice-versa); B troca corrigir por reafirmar." },

{ id:"pt_q03", disc:"pt", top:"Homônimos",
  stem:"Complete: “A ___ de julgamento discutiu a ___ de direitos na ___ de mapas do instituto.” A sequência correta é:",
  alts:["sessão – cessão – seção","seção – sessão – cessão","cessão – seção – sessão","sessão – seção – cessão","seção – cessão – sessão"],
  correct:0,
  why:"Sessão = reunião (sessão de julgamento); cessão = ato de ceder (cessão de direitos); seção = divisão, departamento (seção de mapas). Macete: sesSÃO é reunião em SAlÃO; SEção é SEtor; CEssão é CEder." },

{ id:"pt_q04", disc:"pt", top:"Pontuação",
  stem:"Assinale a frase com ERRO de pontuação:",
  alts:["Os dados coletados na região Norte, segundo o relatório, superaram a meta.","O recenseador, que chegou cedo, iniciou a coleta pelo bairro central.","Os moradores do conjunto habitacional, responderam ao questionário completo.","Concluída a apuração, os resultados foram enviados à coordenação.","O IBGE divulgou os resultados; a imprensa repercutiu os números."],
  correct:2,
  why:"Em C, a vírgula separa o sujeito (“Os moradores do conjunto habitacional”) do verbo (“responderam”) — proibição absoluta da norma. Nas demais: intercalação (A), adjetiva explicativa (B), oração reduzida deslocada (D) e ponto e vírgula entre orações independentes (E), todos corretos." },

{ id:"pt_q05", disc:"pt", top:"Pontuação",
  stem:"Em “O Censo Agropecuário, décimo segundo da série histórica, começa em setembro”, as vírgulas isolam:",
  alts:["um vocativo.","um aposto explicativo.","um adjunto adverbial deslocado.","uma oração subordinada adjetiva restritiva.","um predicativo do sujeito."],
  correct:1,
  why:"“Décimo segundo da série histórica” é termo nominal que explica/identifica “o Censo Agropecuário” — aposto explicativo, sempre entre vírgulas. Vocativo seria um chamamento; restritiva não admite vírgulas; não há circunstância (adjunto adverbial) nem verbo de ligação (predicativo)." },

{ id:"pt_q06", disc:"pt", top:"Ortografia (porquês)",
  stem:"Assinale a frase corretamente grafada:",
  alts:["Não sei por quê o sistema travou durante a coleta.","O supervisor perguntou o porquê da ausência de dados.","Porque você não enviou o relatório ontem?","O formulário foi refeito por que continha erros.","Ele explicou o por quê de cada procedimento."],
  correct:1,
  why:"“O porquê” substantivado (precedido de artigo) escreve-se junto e com acento — correto em B. Em A seria “por que” (meio de frase, sem pausa final); em C, pergunta pede “Por que”; em D, causa pede “porque”; em E, com artigo, seria “o porquê”." },

{ id:"pt_q07", disc:"pt", top:"Acentuação",
  stem:"Conforme a ortografia oficial vigente, assinale a opção em que TODAS as palavras estão corretas:",
  alts:["idéia, heróico, assembléia","ideia, heroico, papéis","ideia, heróico, feiúra","idéia, heroico, papeis","ideia, heroico, papeis"],
  correct:1,
  why:"O Acordo Ortográfico eliminou o acento dos ditongos abertos éi/ói apenas nas PAROXÍTONAS (ideia, heroico, assembleia). Nas oxítonas e monossílabos tônicos o acento permanece: papéis, herói, anéis. “Feiúra” também perdeu o acento (feiura)." },

{ id:"pt_q08", disc:"pt", top:"Classes de palavras",
  stem:"Em “A equipe ficou <em>meio</em> preocupada com as <em>meias</em> respostas do entrevistado”, os termos destacados são, respectivamente:",
  alts:["advérbio (invariável) e adjetivo (variável).","numeral e advérbio.","adjetivo e numeral.","advérbio e advérbio.","numeral e adjetivo."],
  correct:0,
  why:"“Meio” = “um pouco” modifica o adjetivo “preocupada” → advérbio, invariável (nunca “meia preocupada”). “Meias” = incompletas, caracteriza “respostas” → adjetivo, variável. É a pegadinha mais recorrente do tema classes pelo contexto." },

{ id:"pt_q09", disc:"pt", top:"Concordância verbal",
  stem:"Assinale a frase que respeita a concordância verbal:",
  alts:["Haviam muitos domicílios fechados naquele setor censitário.","Fazem dois anos que o instituto atualizou a malha territorial.","Devem haver soluções para os setores de difícil acesso.","Há, nos registros do instituto, informações de todos os municípios.","Existe, segundo os relatórios, várias inconsistências nos dados."],
  correct:3,
  why:"“Haver” no sentido de existir é impessoal: fica na 3ª pessoa do singular (Há informações) — correto em D. Por isso A e C erram (haviam/devem haver); “fazer” temporal também é impessoal (Faz dois anos), derrubando B; “existir” é pessoal e concorda: “Existem várias inconsistências” (E errada)." },

{ id:"pt_q10", disc:"pt", top:"Concordância nominal",
  stem:"Assinale a opção correta quanto à concordância nominal:",
  alts:["Seguem anexo as planilhas solicitadas pela coordenação.","É proibida entrada de pessoas não autorizadas no setor.","As certidões seguem anexas ao processo, conforme solicitado.","Os relatórios estão incluso no pacote enviado ontem.","Ela mesma conferiu os dados, e ele também conferiu ela mesma."],
  correct:2,
  why:"“Anexo” e “incluso” são adjetivos e concordam com o substantivo: “as certidões anexas” (C correta; A e D erradas). Em B, sem artigo o correto é “É proibido entrada”; com artigo, “É proibida a entrada”. E mistura construções e usa “ela” como objeto direto, inadequado à norma culta." },

{ id:"pt_q11", disc:"pt", top:"Regência verbal",
  stem:"Assinale a frase que atende à regência da norma culta:",
  alts:["Todos assistiram o treinamento na sede regional.","O novo procedimento visa melhorar a qualidade dos dados coletados.","O coordenador prefere mais revisar do que digitar.","Chegamos no município às oito horas da manhã.","O supervisor informou os agentes que a rota mudaria."],
  correct:1,
  why:"“Visar” no sentido de objetivar admite (e modernamente consagra) o infinitivo direto: “visa melhorar” — correta. “Assistir” (ver) pede A (assistiram AO treinamento); “preferir” não aceita “mais…do que” (prefere revisar A digitar); “chegar” pede A (chegamos AO município); “informar” pede objeto direto e indireto (informou AOS agentes que…/informou os agentes DE que…)." },

{ id:"pt_q12", disc:"pt", top:"Crase",
  stem:"Assinale a opção em que o sinal de crase está corretamente empregado:",
  alts:["Entregamos o relatório à ela ontem à tarde.","O instituto atende de segunda à sexta, das 8h às 17h.","Os dados serão divulgados à partir de dezembro.","A coleta será feita porta à porta em todo o município.","Encaminhamos a demanda à Coordenação de Geografia."],
  correct:4,
  why:"Crase = preposição “a” + artigo “a”: “encaminhar a (prep.) + a Coordenação” → à. Não há crase antes de pronome pessoal (A), na expressão “de segunda a sexta” sem artigo (B), antes de verbo (“a partir”, C) nem entre palavras repetidas (“porta a porta”, D). Em B, apenas “às 17h” estaria correto — “à sexta” não." },

{ id:"pt_q13", disc:"pt", top:"Verbos",
  stem:"Assinale a frase com o emprego verbal correto:",
  alts:["Quando você ver o supervisor, avise-o da reunião.","Se ele manter a agenda, concluiremos a coleta no prazo.","Quando eu vir as planilhas, valido os totais imediatamente.","Se nós intervirmos agora, evitamos o atraso.","Quando eles porem os dados no sistema, o painel atualizará."],
  correct:2,
  why:"Futuro do subjuntivo de VER = vir (quando eu vir, quando você vir); de MANTER = mantiver; de INTERVIR = intervier(mos); de PÔR = puserem. Só C está correta. Esses quatro verbos (ver, vir, manter/ter, pôr e derivados) são o alvo predileto do tema verbos anômalos/irregulares." },

{ id:"pt_q14", disc:"pt", top:"Vozes verbais",
  stem:"Transpondo para a voz passiva a frase “Os agentes censitários coletarão os dados de todos os domicílios”, obtém-se:",
  alts:["Os dados de todos os domicílios serão coletados pelos agentes censitários.","Os dados de todos os domicílios foram coletados pelos agentes censitários.","Coletar-se-ão os agentes censitários pelos dados dos domicílios.","Os agentes censitários serão coletados pelos dados dos domicílios.","Os dados de todos os domicílios seriam coletados pelos agentes censitários."],
  correct:0,
  why:"Na passiva, o objeto direto vira sujeito e o tempo verbal se mantém: coletarão (futuro do presente) → serão coletados. B muda para pretérito, E para futuro do pretérito, C e D invertem os papéis semânticos — armadilhas padrão da transposição de vozes." },

{ id:"pt_q15", disc:"pt", top:"Colocação pronominal",
  stem:"Assinale a frase que respeita a colocação pronominal da norma culta:",
  alts:["Não entregaram-me os formulários preenchidos.","Aqui trabalha-se com prazos rigorosos.","Me informaram que a reunião foi adiada.","Jamais se questionou a qualidade dos dados do instituto.","Os agentes que apresentaram-se ontem iniciam hoje."],
  correct:3,
  why:"Palavras negativas (não, nunca, jamais), advérbios e pronome relativo “que” atraem o pronome (próclise). “Jamais SE questionou” está correta. A (não…-me), B (aqui…-se) e E (que…-se) violam a atração; C começa período com pronome átono, vedado na norma culta." },

{ id:"pt_q16", disc:"pt", top:"Sintaxe",
  stem:"Em “O supervisor entregou aos recenseadores os novos mapas do setor”, os termos “aos recenseadores” e “os novos mapas do setor” são, respectivamente:",
  alts:["objeto direto e objeto indireto.","objeto indireto e objeto direto.","complemento nominal e objeto direto.","objeto indireto e predicativo do objeto.","adjunto adverbial e objeto direto."],
  correct:1,
  why:"“Entregar” é bitransitivo (VTDI): entrega-se ALGO (objeto direto: os novos mapas) A ALGUÉM (objeto indireto: aos recenseadores). A ordem invertida na frase é justamente a isca — identifique pela pergunta ao verbo, não pela posição." },

{ id:"pt_q17", disc:"pt", top:"Coesão",
  stem:"Em “A coleta atrasou em três setores; <em>não obstante</em>, a meta mensal foi cumprida”, o conector destacado expressa valor de:",
  alts:["causa.","conclusão.","concessão/oposição.","condição.","proporção."],
  correct:2,
  why:"“Não obstante” = apesar disso: introduz ideia que contraria a expectativa criada pela primeira oração (atrasou, MAS a meta foi cumprida) — valor concessivo/adversativo. Equivale a “contudo”, “entretanto”, “apesar disso”." },

{ id:"pt_q18", disc:"pt", top:"Redação oficial",
  stem:"Um Analista do IBGE redige ofício a um colega de mesma hierarquia em outra superintendência. Quanto ao tratamento e ao fecho, o correto é:",
  alts:["Vossa Excelência … Respeitosamente.","Vossa Senhoria … Atenciosamente.","Vossa Senhoria … Respeitosamente.","Vossa Excelência … Atenciosamente.","Vossa Magnificência … Cordialmente."],
  correct:1,
  why:"Servidor sem tratamento especial recebe “Vossa Senhoria”; entre mesma hierarquia (ou para inferior), o fecho é “Atenciosamente” — “Respeitosamente” fica para autoridade superior. “Vossa Magnificência” é exclusivo de reitores; “Cordialmente” não integra o padrão oficial." },

/* ============ RACIOCÍNIO LÓGICO (12) ============ */
{ id:"rl_q01", disc:"rlq", top:"Negação de condicional",
  stem:"A negação de “Se o setor é urbano, então a coleta é presencial” é:",
  alts:["Se o setor não é urbano, então a coleta não é presencial.","O setor é urbano e a coleta não é presencial.","O setor não é urbano ou a coleta é presencial.","Se a coleta não é presencial, então o setor não é urbano.","O setor não é urbano e a coleta não é presencial."],
  correct:1,
  why:"~(p→q) = p ∧ ~q: mantém a primeira E nega a segunda (“urbano E não presencial”). Negar condicional NUNCA gera outro “se…então” — A e D são, respectivamente, o erro clássico e a equivalência contrapositiva (não a negação); C é a forma equivalente de p→q (~p∨q)." },

{ id:"rl_q02", disc:"rlq", top:"Equivalência lógica",
  stem:"A proposição “Se o questionário está completo, então o domicílio é validado” é logicamente equivalente a:",
  alts:["Se o domicílio é validado, então o questionário está completo.","O questionário está completo e o domicílio é validado.","Se o domicílio não é validado, então o questionário não está completo.","O questionário não está completo ou o domicílio não é validado.","Se o questionário não está completo, então o domicílio não é validado."],
  correct:2,
  why:"p→q ≡ ~q→~p (contrapositiva: inverte E nega). Também vale p→q ≡ ~p∨q. A e E são erros clássicos (recíproca e inversa não são equivalentes); D nega o termo errado da disjunção." },

{ id:"rl_q03", disc:"rlq", top:"Negação de quantificador",
  stem:"A negação de “Todos os recenseadores concluíram o treinamento” é:",
  alts:["Nenhum recenseador concluiu o treinamento.","Todos os recenseadores não concluíram o treinamento.","Algum recenseador não concluiu o treinamento.","Algum recenseador concluiu o treinamento.","Existe recenseador que concluiu o treinamento."],
  correct:2,
  why:"~(Todo A é B) = Algum A não é B — basta UMA exceção para derrubar o “todos”. “Nenhum” (A) é o extremo oposto, não a negação; é a pegadinha número 1 dos quantificadores." },

{ id:"rl_q04", disc:"rlq", top:"Diagramas lógicos",
  stem:"Considere verdadeiras: “Todo analista é concursado” e “Algum concursado é estatístico”. Conclui-se necessariamente que:",
  alts:["algum analista é estatístico.","todo estatístico é concursado.","algum estatístico não é analista.","nenhuma das conclusões anteriores é necessária.","nenhum analista é estatístico."],
  correct:3,
  why:"O “algum concursado estatístico” pode estar dentro OU fora do círculo dos analistas — os diagramas admitem ambas as configurações, então nada se conclui com necessidade sobre analistas × estatísticos. Questão clássica de premissas com “todo + algum” encadeados pelo termo médio." },

{ id:"rl_q05", disc:"rlq", top:"Tabela-verdade",
  stem:"Sendo p verdadeira, q falsa e r falsa, o valor lógico de (p ∨ q) → (q ∧ r) é:",
  alts:["verdadeiro, pois a disjunção é falsa.","verdadeiro, pois a conjunção é verdadeira.","falso, pois V → F é falso.","falso, pois F → F é falso.","indeterminado sem a tabela completa."],
  correct:2,
  why:"p∨q = V∨F = V; q∧r = F∧F = F. Condicional V→F é o ÚNICO caso falso do “se…então”. Memorize: a condicional só “quebra” quando a promessa é feita (V) e não cumprida (F)." },

{ id:"rl_q06", disc:"rlq", top:"Argumentação",
  stem:"Premissas: “Se chove, o acesso ao setor rural fica interditado” e “O acesso ao setor rural não ficou interditado”. Logo:",
  alts:["choveu.","não choveu.","o acesso ficou parcialmente livre.","se não chove, o acesso fica liberado.","nada se conclui."],
  correct:1,
  why:"Modus tollens: p→q com ~q permite concluir ~p. Se a consequência não ocorreu, o antecedente não pode ter ocorrido. Cuidado com o erro inverso (afirmar o consequente): de q verdadeiro NÃO se conclui p." },

{ id:"rl_q07", disc:"rlq", top:"Verdades e mentiras",
  stem:"Três agentes deram um depoimento cada. Ana: “Bruno mente”. Bruno: “Carla mente”. Carla: “Ana e Bruno mentem”. Sabendo que exatamente um fala a verdade, quem é?",
  alts:["Ana.","Bruno.","Carla.","Ana e Bruno.","Impossível determinar."],
  correct:1,
  why:"Teste Bruno verdadeiro: então Carla mente (ok) e, como só há um veraz, Ana mente — logo “Bruno mente” é falso, coerente. Verificação: Carla mentirosa significa que NÃO é verdade que ambos mentem — de fato Bruno fala verdade. Testar Ana ou Carla como verazes gera contradição. Método: hipótese + verificação de consistência." },

{ id:"rl_q08", disc:"rlq", top:"Porcentagem",
  stem:"Uma meta de coleta foi aumentada em 20% e, no mês seguinte, reduzida em 20% sobre o novo valor. Em relação à meta original, o valor final é:",
  alts:["igual à original.","4% menor.","4% maior.","20% menor.","2% menor."],
  correct:1,
  why:"1,20 × 0,80 = 0,96 → 4% a menos. Aumentos e descontos percentuais sucessivos MULTIPLICAM fatores, nunca se somam/cancelam — a alternativa “igual à original” está lá para punir a conta de cabeça errada." },

{ id:"rl_q09", disc:"rlq", top:"Regra de três composta",
  stem:"Se 6 recenseadores visitam 480 domicílios em 8 dias, quantos domicílios 9 recenseadores visitam em 10 dias, no mesmo ritmo?",
  alts:["720","800","900","960","1080"],
  correct:2,
  why:"Produtividade por recenseador-dia: 480 ÷ (6×8) = 10 domicílios. Então 9 × 10 × 10 = 900. Grandezas diretamente proporcionais ao trabalho: multiplica-se tudo — o método do “rendimento unitário” evita erro de montagem da proporção." },

{ id:"rl_q10", disc:"rlq", top:"Médias",
  stem:"A média de idade de 4 agentes é 30 anos. Com a chegada de um quinto agente, a média sobe para 32 anos. A idade do novo agente é:",
  alts:["34","36","38","40","42"],
  correct:3,
  why:"Soma antes: 4×30 = 120. Soma depois: 5×32 = 160. Novo agente: 160 − 120 = 40. Trabalhe sempre com as SOMAS, não com as médias — é o atalho que resolve toda variação de média por inclusão/exclusão." },

{ id:"rl_q11", disc:"rlq", top:"Sequências",
  stem:"Na sequência 3, 7, 15, 31, 63, …, o próximo termo é:",
  alts:["95","111","125","127","129"],
  correct:3,
  why:"Cada termo = dobro do anterior + 1 (3→7→15→31→63→127). Alternativa: as diferenças (4, 8, 16, 32) dobram, próxima diferença 64 → 63+64 = 127. Padrões multiplicativos disfarçados são a marca das questões de sequência." },

{ id:"rl_q12", disc:"rlq", top:"Conjuntos",
  stem:"Entre 200 moradores entrevistados, 120 têm acesso à internet fixa, 90 à internet móvel e 60 a ambas. Quantos NÃO têm acesso a nenhuma das duas?",
  alts:["10","30","50","60","80"],
  correct:2,
  why:"União = 120 + 90 − 60 = 150 têm pelo menos uma. Nenhuma = 200 − 150 = 50. As iscas: 30 (120−90), 60 (a interseção) e 80 (200−120). Sempre: interseção primeiro, união pela fórmula, “nenhum” = universo − união." },

/* ============ CONHECIMENTOS ESPECÍFICOS (30) ============ */
{ id:"es_q01", disc:"esp", top:"Preparação de originais",
  stem:"Na produção editorial, a “preparação de originais” consiste em:",
  alts:["imprimir a prova final para aprovação do cliente.","normalizar e padronizar o texto (hierarquia de títulos, realces, notas) antes da composição/diagramação.","corrigir o texto já diagramado, comparando-o com a prova impressa.","criar o projeto gráfico da capa e definir o papel do miolo.","gravar as chapas de impressão a partir do arquivo fechado."],
  correct:1,
  why:"Preparação de originais é a etapa PRÉ-composição: padronizar grafias, hierarquizar títulos e itens, marcar realces (itálico/negrito), organizar notas e citações. Corrigir texto já diagramado é revisão de provas; chapas e provas finais são etapas de pré-impressão/impressão." },

{ id:"es_q02", disc:"esp", top:"Revisão",
  stem:"A diferença essencial entre copidesque e revisão tipográfica (revisão de provas) é:",
  alts:["o copidesque ocorre após a impressão; a revisão, antes.","o copidesque aprimora o texto original (estilo, clareza, normalização); a revisão de provas confere o texto já composto/diagramado contra o original.","a revisão de provas altera o conteúdo autoral; o copidesque só marca erros de quebra.","ambos são sinônimos, variando apenas o suporte (papel ou tela).","o copidesque é feito pelo gráfico; a revisão, pelo autor."],
  correct:1,
  why:"Copidesque (copy desk) trabalha o ORIGINAL: estilo, coesão, normalização. Revisão tipográfica confere as PROVAS da composição: quebras, hifenização, viúvas/órfãs, fidelidade ao original — usando os sinais de revisão padronizados." },

{ id:"es_q03", disc:"esp", top:"Sinais de revisão",
  stem:"Nos sinais de revisão padronizados, o sinal “deleatur” indica:",
  alts:["trocar a ordem de palavras ou letras.","suprimir/eliminar letra, palavra ou trecho.","juntar o que está separado.","abrir novo parágrafo.","alinhar o texto à esquerda."],
  correct:1,
  why:"Deleatur (do latim “que se apague”) é o sinal clássico de SUPRESSÃO — um risco com laço característico. Transposição, união, novo parágrafo e alinhamento têm sinais próprios distintos. É o sinal mais cobrado da tabela." },

{ id:"es_q04", disc:"esp", top:"Alinhamentos",
  stem:"O alinhamento em que todas as linhas do parágrafo se estendem igualmente das margens esquerda à direita (com ajuste dos espaços entre palavras) denomina-se:",
  alts:["alinhado à esquerda (quebra irregular à direita).","centralizado.","justificado (blocado).","alinhado à direita.","assimétrico."],
  correct:2,
  why:"Justificado (ou blocado): as linhas fecham nas duas margens, com o espaçamento entre palavras variando para compensar — padrão de livros e jornais. Cuidado com o efeito colateral cobrado junto: “rios” e espaços exagerados em colunas estreitas." },

{ id:"es_q05", disc:"esp", top:"Editoração/ABNT",
  stem:"Segundo as noções básicas de editoração da ABNT, os elementos de um livro dividem-se em pré-textuais, textuais e pós-textuais. São exemplos de elementos PRÉ-textuais:",
  alts:["índice e glossário.","folha de rosto e sumário.","referências e apêndices.","posfácio e colofão.","capítulos e conclusão."],
  correct:1,
  why:"Pré-textuais antecedem o texto: falsa folha de rosto, folha de rosto, ficha catalográfica, dedicatória, epígrafe, sumário. Referências, glossário, apêndices, índice e colofão são PÓS-textuais; capítulos e conclusão são o próprio texto." },

{ id:"es_q06", disc:"esp", top:"Composição",
  stem:"Sobre os tipos de composição, a sequência histórica correta é:",
  alts:["fotocomposição → composição manual → composição digital → linotipo.","composição manual (tipos móveis) → composição mecânica (linotipo/monotipo) → fotocomposição → editoração eletrônica (digital).","linotipo → tipos móveis → editoração eletrônica → fotocomposição.","editoração eletrônica → fotocomposição → monotipo → tipos móveis.","monotipo → fotocomposição → tipos móveis → digital."],
  correct:1,
  why:"Evolução: tipos móveis de Gutenberg (manual) → máquinas de compor a quente, linotipo (linhas inteiras) e monotipo (tipos avulsos) → fotocomposição (matrizes fotográficas) → editoração eletrônica/desktop publishing. A banca adora pedir a ordem ou a diferença linotipo × monotipo." },

{ id:"es_q07", disc:"esp", top:"Projeto gráfico",
  stem:"No projeto gráfico-editorial, “boneca” é:",
  alts:["o arquivo digital final enviado à gráfica.","a miniatura/maquete física ou esboço página a página que simula a publicação (formato, paginação, distribuição do conteúdo).","a prova de cor contratual assinada pelo cliente.","o conjunto de fontes utilizado no projeto.","a chapa de alumínio gravada para offset."],
  correct:1,
  why:"Boneca é a maquete da publicação: mostra formato, número de páginas, imposição do conteúdo — usada para planejar e aprovar antes da arte-final. Arquivo final = arte-final; prova contratual e chapa pertencem à pré-impressão." },

{ id:"es_q08", disc:"esp", top:"Arte-final",
  stem:"Denomina-se “arte-final” o material que:",
  alts:["está pronto para a reprodução gráfica, com textos, imagens e marcas técnicas definitivos.","ainda receberá revisão de conteúdo e ajustes de layout.","corresponde ao rascunho inicial apresentado ao cliente.","é impresso em baixa resolução para conferência interna.","reúne apenas as imagens em alta resolução, sem os textos."],
  correct:0,
  why:"Arte-final é o estágio FINAL da arte: tudo fechado e tecnicamente pronto para reprodução (hoje, o PDF/X com sangria e marcas). Rascunho é o rafe/layout; conferência interna é prova. “Final” no nome já entrega o conceito — a banca troca por etapas anteriores." },

{ id:"es_q09", disc:"esp", top:"Diagramação",
  stem:"Na diagramação, o “grid” (malha/diagrama) tem a função de:",
  alts:["definir a lineatura da retícula de impressão.","estruturar a página em colunas, módulos e margens, dando consistência à distribuição de textos e imagens.","calibrar as cores do monitor para a prova digital.","determinar a gramatura do papel do miolo.","converter as fontes em curvas no fechamento."],
  correct:1,
  why:"O grid é a estrutura invisível da página: colunas, módulos, margens e entrelinhas-base que organizam o conteúdo com consistência entre páginas. Lineatura, calibração, gramatura e curvas pertencem a outras etapas — associação indevida é o padrão das alternativas erradas." },

{ id:"es_q10", disc:"esp", top:"Tipologia",
  stem:"Sobre classificação tipográfica, é correto afirmar:",
  alts:["fontes serifadas não possuem os pequenos traços de remate; as sans serif os possuem.","Times New Roman e Garamond são exemplos clássicos de fontes sem serifa.","Helvetica, Arial e Futura são exemplos de fontes sem serifa (sans serif).","fontes manuscritas (script) são as mais indicadas para longos textos de livro.","itálico e negrito são famílias tipográficas independentes, sem relação com a fonte base."],
  correct:2,
  why:"Sans serif = sem os remates (Helvetica, Arial, Futura, Univers); serifadas = com remates (Times, Garamond, Bodoni), tradicionais para texto longo impresso. Itálico/negrito são VARIAÇÕES dentro da família. A confusão serifa × sem serifa invertida é a pegadinha básica." },

{ id:"es_q11", disc:"esp", top:"Medidas tipográficas",
  stem:"No sistema de medidas tipográficas anglo-americano, uma paica equivale a:",
  alts:["6 pontos.","10 pontos.","12 pontos.","12 cíceros.","72 pontos."],
  correct:2,
  why:"1 paica = 12 pontos; 1 polegada = 6 paicas = 72 pontos (por isso corpo 72 ≈ 1 polegada). O cícero é o correspondente do sistema europeu Didot (também 12 pontos Didot). Decore o trio 12–6–72: cai literalmente." },

{ id:"es_q12", disc:"esp", top:"Entrelinha",
  stem:"Em tipografia, “entrelinha” (leading) é:",
  alts:["o espaço entre pares específicos de letras.","a distância vertical entre as linhas de base do texto.","a largura total da coluna de texto.","o espaço entre palavras na linha justificada.","a altura das letras minúsculas sem ascendentes."],
  correct:1,
  why:"Entrelinha = distância entre linhas de base consecutivas (ex.: corpo 10/12 = corpo 10 com entrelinha 12). Espaço entre pares de letras é kerning; entre todas as letras, tracking; altura das minúsculas é a altura-x. A banca cobra esse vocabulário por definição cruzada." },

{ id:"es_q13", disc:"esp", top:"Papel",
  stem:"A gramatura do papel expressa:",
  alts:["a espessura da folha, em milímetros.","o peso em gramas de uma folha de 1 m² do papel (g/m²).","o grau de brancura da superfície.","a resistência à tração no sentido das fibras.","o número de folhas por resma."],
  correct:1,
  why:"Gramatura = massa por área: g/m². Um couché 150 g/m² significa que 1 m² dessa folha pesa 150 g. Espessura é outra grandeza (calibre/micrometria) — papéis de mesma gramatura podem ter espessuras diferentes (papéis de alto volume)." },

{ id:"es_q14", disc:"esp", top:"Formatos de papel",
  stem:"Sobre a série A de formatos (ISO 216), é correto afirmar:",
  alts:["o A4 mede 210 × 297 mm e o A0 tem área de 1 m².","o A4 mede 216 × 279 mm, padrão carta.","o A3 é a metade do A4.","o A0 mede 500 × 700 mm.","cada formato da série dobra a largura do anterior, mantendo a altura."],
  correct:0,
  why:"A série A parte do A0 = 841 × 1189 mm (1 m² de área); cada número seguinte é a METADE do anterior (A3 é o dobro do A4, não a metade). 216 × 279 mm é o formato Carta (americano). Os formatos gráficos brasileiros de folha inteira incluem o 66 × 96 cm." },

{ id:"es_q15", disc:"esp", top:"Tipos de papel",
  stem:"Comparando os papéis couché e offset:",
  alts:["o couché recebe revestimento mineral que melhora a reprodução de imagens; o offset é não revestido, indicado para textos e escrita.","o offset é revestido e brilhante; o couché é áspero e absorvente.","ambos são revestidos, diferindo apenas na gramatura.","o couché não aceita impressão em policromia.","o offset é usado exclusivamente em impressão digital."],
  correct:0,
  why:"Couché = revestido (coated): superfície lisa, ótima definição de imagem, em versões brilho e fosco — padrão de revistas. Offset (apergaminhado) = não revestido, mais absorvente e apto à escrita — padrão de miolos de livro e papelaria. Nome do papel ≠ processo offset: os dois se imprimem em offset." },

{ id:"es_q16", disc:"esp", top:"Provas",
  stem:"Cromalin e Matchprint são exemplos de:",
  alts:["provas de prelo, feitas na própria máquina de impressão com as tintas da tiragem.","provas pré-impressão (analógicas, à base do fotolito) usadas como referência contratual de cor.","sistemas de acabamento por laminação.","tipos de retícula estocástica.","chapas de impressão sem processamento químico."],
  correct:1,
  why:"Cromalin (DuPont) e Matchprint (3M/Kodak) são provas de PRÉ-impressão feitas a partir dos fotolitos — serviam de prova contratual de cor. Prova de prelo é a que roda na própria impressora offset, com papel e tinta da tiragem — mais fiel e mais cara. Distinção literal do edital." },

{ id:"es_q17", disc:"esp", top:"Fotolito",
  stem:"No fluxo gráfico tradicional, o fotolito é:",
  alts:["a chapa de alumínio que vai à impressora.","o filme transparente (matriz fotográfica), com uma lâmina por cor, usado para gravar as chapas de impressão.","a prova digital colorida de baixa resolução.","o cilindro revestido de borracha que transfere a tinta.","o software de imposição de páginas."],
  correct:1,
  why:"Fotolito = filme matriz: para policromia, quatro filmes (C, M, Y, K) reticulados que gravam as chapas por contato/exposição. Foi substituído pelo CTP (computer-to-plate), que grava a chapa direto do arquivo — comparação fotolito × CTP é pergunta recorrente. O cilindro de borracha é a blanqueta." },

{ id:"es_q18", disc:"esp", top:"Retícula",
  stem:"A função da retícula na impressão é:",
  alts:["aumentar a gramatura aparente do papel.","converter tons contínuos em pontos imprimíveis, simulando variações de tom pela variação dos pontos.","alinhar as chapas na impressora (registro).","proteger a impressão contra abrasão.","transformar imagens RGB em vetores."],
  correct:1,
  why:"Impressoras não imprimem “meio-tom” contínuo: a retícula decompõe a imagem em pontos. Na retícula convencional (AM) varia o TAMANHO do ponto em malha fixa; na estocástica (FM) varia a FREQUÊNCIA de micropontos de tamanho igual. AM × FM é o desdobramento clássico da questão." },

{ id:"es_q19", disc:"esp", top:"Policromia",
  stem:"Sobre policromia e cores especiais:",
  alts:["a policromia usa as quatro cores de escala (CMYK); cores especiais (ex.: Pantone) são tintas prontas usadas quando a escala não reproduz a cor desejada com fidelidade.","a policromia usa RGB e as cores especiais usam CMYK.","Pantone é o nome comercial da tinta preta de escala.","cores especiais são sempre mais baratas por dispensarem chapas.","a policromia exige no mínimo seis tintas."],
  correct:0,
  why:"Policromia = seleção de cores em CMYK (quadricromia). Cores fora do gamut CMYK (laranjas vivos, metálicos, fluorescentes, cor institucional exata) pedem tinta especial/spot — catálogo Pantone —, que exige chapa própria (5ª cor), encarecendo. RGB é cor-luz de tela, nunca tinta." },

{ id:"es_q20", disc:"esp", top:"Sistemas de cor",
  stem:"Sobre os sistemas RGB e CMYK, é correto:",
  alts:["RGB é sistema subtrativo usado em impressão.","CMYK é sistema aditivo usado em monitores.","RGB é aditivo (cor-luz, telas); CMYK é subtrativo (cor-pigmento, impressão) — e a soma das luzes RGB produz o branco.","nos dois sistemas, a soma de todas as cores resulta em preto.","a conversão de RGB para CMYK amplia a gama de cores disponível."],
  correct:2,
  why:"RGB: luzes que se SOMAM — juntas dão branco (aditivo). CMYK: pigmentos que SUBTRAEM luz — teoricamente juntos dão preto (o K entra pela impureza das tintas e economia). Converter RGB→CMYK REDUZ o gamut — cores de tela “apagam” no papel, por isso o alerta do preflight." },

{ id:"es_q21", disc:"esp", top:"Offset",
  stem:"O princípio do processo offset é:",
  alts:["gravação em relevo, como na tipografia.","incisão em profundidade no cilindro, como na rotogravura.","repulsão entre água e gordura em chapa plana, com transferência INDIRETA da imagem por um cilindro intermediário (blanqueta).","perfuração de tela para passagem da tinta, como na serigrafia.","fusão de toner por calor, como na eletrografia."],
  correct:2,
  why:"Offset é planográfico: área de imagem oleófila (aceita tinta gordurosa), área de contragrafismo hidrófila (aceita água). A imagem vai da chapa à BLANQUETA (borracha) e desta ao papel — “offset” = fora do contato direto. Relevo = tipografia; entalhe = rotogravura; permeação = serigrafia; toner = digital eletrográfico." },

{ id:"es_q22", disc:"esp", top:"Impressão digital",
  stem:"Uma vantagem característica da impressão digital sobre o offset convencional é:",
  alts:["menor custo unitário em tiragens muito grandes.","viabilizar tiragens curtas e dado variável (personalização), por dispensar chapas e acertos.","maior fidelidade obrigatória de cores especiais metálicas.","uso exclusivo de papéis revestidos.","não exigir arquivo digital."],
  correct:1,
  why:"Sem chapa e sem acerto de máquina, a digital tem custo de partida baixo: ideal para tiragem curta, prazo apertado e DADO VARIÁVEL (cada exemplar diferente — nomes, códigos). Em altas tiragens o offset vence no custo unitário — a relação inverte, e é exatamente isso que a banca pergunta." },

{ id:"es_q23", disc:"esp", top:"Plotter e corte",
  stem:"No contexto dos processos digitais diversos citados no edital, plotter e corte eletrônico associam-se, respectivamente, a:",
  alts:["impressão de grandes formatos (banners, adesivos) e recorte de mídias como vinil por lâmina controlada digitalmente.","impressão de livros em altíssima tiragem e costura de cadernos.","gravação de chapas offset e dobra de folhas.","provas contratuais de cor e laminação fosca.","impressão em relevo e douração a quente."],
  correct:0,
  why:"Plotter imprime grandes formatos (comunicação visual: banners, lonas, adesivos); a plotter de corte/corte eletrônico recorta vinil e outras mídias seguindo o vetor do arquivo — dupla da sinalização e do grande formato. As demais alternativas misturam etapas de acabamento e pré-impressão." },

{ id:"es_q24", disc:"esp", top:"Acabamento",
  stem:"Sobre acabamento gráfico, é correto afirmar:",
  alts:["a laminação e o verniz UV são aplicados antes da impressão.","em papéis de alta gramatura, o vinco deve preceder a dobra para evitar o craqueamento da fibra.","a encadernação em canoa usa cola PUR no lombo.","o refile é a aplicação de brilho localizado.","a dobra é sempre a última operação do acabamento."],
  correct:1,
  why:"Vincar antes de dobrar é regra para gramaturas altas (a partir de ~170 g/m²): o vinco comprime as fibras e impede o estouro da dobra. Laminação/verniz vêm DEPOIS de impresso; canoa = grampo no lombo (cola PUR é brochura); refile = corte final nas guias." },

{ id:"es_q25", disc:"esp", top:"Controle de qualidade",
  stem:"Nas laterais de uma folha impressa em offset costuma haver uma barra com quadrados das cores de escala. Sua função é:",
  alts:["decorar a área de refile.","permitir o controle de qualidade da impressão (densidade de tinta, ganho de ponto, registro) com instrumentos como o densitômetro.","indicar a gramatura do papel utilizado.","marcar a posição da lombada.","substituir as marcas de corte."],
  correct:1,
  why:"É a barra (tira) de controle: por ela o impressor mede densidade das tintas, ganho de ponto, trapping e registro — com densitômetro/espectrofotômetro — garantindo constância na tiragem. Fica na área que será refilada, mas sua função é técnica, não decorativa." },

{ id:"es_q26", disc:"esp", top:"E-books",
  stem:"A principal diferença entre os formatos EPUB e PDF para publicações eletrônicas é:",
  alts:["o EPUB é fluido (o texto reflui e se adapta à tela/corpo escolhido); o PDF preserva a diagramação fixa da página.","o PDF é um formato aberto e o EPUB, proprietário da Amazon.","o EPUB não admite imagens nem sumário navegável.","o PDF adapta o texto automaticamente a qualquer tela.","ambos refluem o texto, diferindo só na compressão."],
  correct:0,
  why:"EPUB = reflowable: XHTML+CSS empacotados em ZIP, texto que se adapta ao dispositivo — padrão aberto (IDPF/W3C). PDF = página fixa, fiel ao projeto gráfico. Proprietário da Amazon é o MOBI/AZW. O InDesign CS6 exporta EPUB 2.0.1 e 3.0." },

{ id:"es_q27", disc:"esp", top:"Photoshop CS6",
  stem:"No Photoshop CS6, a diferença entre as ferramentas Clone Stamp (carimbo) e Healing Brush (pincel de recuperação) é:",
  alts:["o carimbo copia a área de origem literalmente; o healing mescla a textura copiada com a cor e a luminosidade do destino.","o healing copia literalmente; o carimbo mescla com o destino.","ambas geram seleções, diferindo na tolerância.","o carimbo funciona apenas em imagens CMYK.","o healing só existe a partir do Photoshop CC."],
  correct:0,
  why:"Clone Stamp = cópia fiel da origem (pode denunciar o retoque). Healing Brush = copia a TEXTURA e a funde com cor/brilho locais do destino — retoque de pele e fundos. Ambos existem desde muito antes do CC. Variante da mesma família: Spot Healing e Patch (com Content-Aware no CS6)." },

{ id:"es_q28", disc:"esp", top:"Photoshop CS6 — versão",
  stem:"São recursos INTRODUZIDOS no Photoshop CS6, EXCETO:",
  alts:["Content-Aware Move.","Blur Gallery (Field, Iris e Tilt-Shift).","recorte (Crop) não destrutivo.","Select Subject (seleção automática do assunto).","salvamento em segundo plano com recuperação automática."],
  correct:3,
  why:"Select Subject é do Photoshop CC (2018) — impossível no CS6 e isca padrão da “pegadinha de versão”. Content-Aware Move, Blur Gallery, Crop não destrutivo, interface escura, Mercury Graphics Engine e auto-save/background save são o pacote de novidades do CS6." },

{ id:"es_q29", disc:"esp", top:"InDesign CS6",
  stem:"No fechamento de arquivo no InDesign CS6, o recurso que reúne o documento, as fontes e as imagens vinculadas numa única pasta para envio é:",
  alts:["Preflight.","Package (Empacotar).","Liquid Layout.","Content Collector.","Export EPUB."],
  correct:1,
  why:"Package/Empacotar junta .indd + links + fontes (+ relatório) para envio à gráfica. Preflight DIAGNOSTICA problemas (RGB, baixa resolução, fonte faltando) mas não junta nada; Liquid Layout adapta layouts a formatos; Content Collector transporta objetos entre documentos." },

{ id:"es_q30", disc:"esp", top:"Illustrator CS6",
  stem:"No Illustrator CS6, o recurso que converte imagens bitmap em desenhos vetoriais é o:",
  alts:["Live Paint.","Image Trace (que substituiu o antigo Live Trace).","Pathfinder.","Create Outlines.","Mesh Tool."],
  correct:1,
  why:"O CS6 estreou o Image Trace, sucessor do Live Trace (este ia até o CS5) — motor novo de vetorização de bitmaps. Pathfinder combina formas; Create Outlines converte TEXTO em curvas; Live Paint pinta regiões; Mesh cria malhas de gradiente. A troca de nome entre versões é a pegadinha." }
];
